# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winddir', models.IntegerField()),
                ('windspeedmph', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('windspdmph_avg2m', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('rainin', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('dailyrainin', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tempf', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date logged')),
            ],
        ),
    ]
