# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170208_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata_weather',
            name='dailyrainin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawdata_weather',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rawdata_weather',
            name='pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawdata_weather',
            name='rainin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawdata_weather',
            name='tempf',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawdata_weather',
            name='windspdmph_avg2m',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawdata_weather',
            name='windspeedmph',
            field=models.FloatField(null=True),
        ),
    ]
