# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170222_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='AMPS_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
